version: "2"
run:
  build-tags:
    - integration
  modules-download-mode: vendor
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/flatcar/flatcar-linux-update-operator)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
linters:
  disable:
    - depguard
    - err113
    - exhaustruct
    - gochecknoglobals
    - godox
    - ireturn
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    godot:
      capital: true
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    makezero:
      always: true
    nolintlint:
      require-explanation: true
      require-specific: true
    varnamelen:
      ignore-names:
        - ok
    wsl:
      force-err-cuddling: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - mnd
        source: klog.V\(
      - linters:
          - lll
        source: http(s)://
      - linters:
          - forbidigo
        path: cmd/
        text: use of `fmt.Printf` forbidden by pattern
      - linters:
          - forbidigo
        path: cmd/
        text: use of `fmt.Println` forbidden by pattern
      - linters:
          - forbidigo
        path: _test.go
        text: use of `fmt.Printf` forbidden by pattern
      - linters:
          - forbidigo
        path: _test.go
        text: use of `fmt.Println` forbidden by pattern
      - linters:
          - wrapcheck
        text: error returned from external package is unwrapped
      - linters:
          - wrapcheck
        text: error returned from interface method should be wrapped
      - linters:
          - paralleltest
        text: does not use range value in test Run
    paths:
      - third_party$
      - builtin$
      - examples$
