output:
  sort-results: true

run:
  modules-download-mode: vendor
  timeout: 5m
  build-tags:
    - integration

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # Ignore magic numbers in klog.V() calls until we clean them up.
    - linters:
        - gomnd
      source: "klog.V\\("
    # Ignore long generate commands.
    - linters:
        - lll
      source: "^\\/\\/go:generate"
    # Ignore URLs in comments.
    - linters:
        - lll
      source: "http(s)://"
    # Allow use of fmt.Print* functions in cmd package and in tests.
    - linters:
        - forbidigo
      text: "use of `fmt.Printf` forbidden by pattern"
      path: cmd/
    - linters:
        - forbidigo
      text: "use of `fmt.Println` forbidden by pattern"
      path: cmd/
    - linters:
        - forbidigo
      text: "use of `fmt.Printf` forbidden by pattern"
      path: "_test.go"
    - linters:
        - forbidigo
      text: "use of `fmt.Println` forbidden by pattern"
      path: "_test.go"
    # Allow to return unwrapped errors from external packages, as we do not use typed errors yet.
    - linters:
        - wrapcheck
      text: "error returned from external package is unwrapped"
    - linters:
        - wrapcheck
      text: "error returned from interface method should be wrapped"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gci:
    local-prefixes: github.com/flatcar-linux/flatcar-linux-update-operator
  godot:
    capital: true
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  makezero:
    always: true
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true
  wsl:
    force-err-cuddling: true

# Update list of enabled linters using 'make update-linters'.
linters:
  disable-all: false
  disable:
    # We use different import grouping style than gci forces.
    - gci
    # We still have many globals to get rid of.
    - gochecknoglobals
    # TODOs in the code are OK.
    - godox
    # We do not have clearly defined error types yet.
    - goerr113
    # We do not require all used structs to have all fields initialized.
    - exhaustivestruct
    # We do not care about the memory efficiency really.
    - maligned
    # We allow returning interfaces for defensive programming.
    - ireturn
    # This linter has been deprecated.
    - interfacer
    # This linter has been deprecated.
    - scopelint
    # This linter has been deprecated.
    - golint
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - ifshort
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
